# Common to Sunstone, OCCI and ECONE
usr/lib/one/ruby/OpenNebulaVNC.rb
usr/bin/novnc-server

# Sunstone
usr/lib/one/sunstone/config.ru
etc/one/sunstone-server.conf
etc/one/sunstone-views.yaml
etc/one/sunstone-views

usr/lib/one/sunstone/*.rb
usr/lib/one/sunstone/models/Sunstone*
usr/lib/one/sunstone/views/
usr/lib/one/sunstone/public/css/
usr/lib/one/sunstone/public/js/
usr/lib/one/sunstone/public/images/
usr/lib/one/sunstone/public/locale/
usr/lib/one/sunstone/routes/

usr/bin/sunstone-server

usr/lib/one/ruby/cloud/CloudAuth/SunstoneCloudAuth.rb
usr/lib/one/ruby/cloud/marketplace/marketplace_client.rb

usr/lib/one/sunstone/public/vendor/crypto-js/
usr/lib/one/sunstone/public/vendor/noVNC/
usr/lib/one/sunstone/public/vendor/spice/

usr/lib/one/sunstone/public/vendor/4.0/

usr/share/one/websockify/

# ECONE
etc/one/econe.conf

etc/one/ec2query_templates/

usr/bin/econe-server

usr/lib/one/ruby/cloud/CloudAuth/EC2CloudAuth.rb

usr/lib/one/ruby/cloud/econe/econe-server.rb
usr/lib/one/ruby/cloud/econe/econe_application.rb
usr/lib/one/ruby/cloud/econe/elastic_ip.rb
usr/lib/one/ruby/cloud/econe/ImageEC2.rb
usr/lib/one/ruby/cloud/econe/EC2QueryServer.rb
usr/lib/one/ruby/cloud/econe/ebs.rb
usr/lib/one/ruby/cloud/econe/instance.rb
usr/lib/one/ruby/cloud/econe/keypair.rb
usr/lib/one/ruby/cloud/econe/net_ssh_replacement.rb
usr/lib/one/ruby/cloud/econe/tags.rb
usr/lib/one/ruby/cloud/econe/views/

usr/bin/econe-allocate-address
usr/bin/econe-associate-address
usr/bin/econe-describe-addresses
usr/bin/econe-describe-images
usr/bin/econe-describe-instances
usr/bin/econe-disassociate-address
usr/bin/econe-register
usr/bin/econe-release-address
usr/bin/econe-run-instances
usr/bin/econe-terminate-instances
usr/bin/econe-upload
usr/bin/econe-attach-volume
usr/bin/econe-create-volume
usr/bin/econe-delete-volume
usr/bin/econe-describe-volumes
usr/bin/econe-detach-volume
usr/bin/econe-reboot-instances
usr/bin/econe-start-instances
usr/bin/econe-stop-instances
usr/bin/econe-create-keypair
usr/bin/econe-delete-keypair
usr/bin/econe-describe-keypairs
