etc/one/auth/server_x509_auth.conf
etc/one/auth/x509_auth.conf
etc/one/auth/ldap_auth.conf

usr/lib/one/ruby/opennebula.rb

usr/lib/one/ruby/OpenNebula.rb

usr/lib/one/ruby/cloud/CloudServer.rb
usr/lib/one/ruby/cloud/CloudAuth.rb
usr/lib/one/ruby/cloud/CloudAuth/OpenNebulaCloudAuth.rb
usr/lib/one/ruby/cloud/CloudAuth/X509CloudAuth.rb

usr/lib/one/ruby/opennebula/

usr/lib/one/sunstone/models/OpenNebulaJSON.rb usr/lib/one/ruby/
usr/lib/one/sunstone/models/OpenNebulaJSON/   usr/lib/one/ruby/

usr/lib/one/ruby/vendors/
usr/lib/one/ruby/vcenter_driver.rb
